import java.util.ArrayList;

/**
 *
 * Date: October 20, 2024.
 * This code was generated by CoPilot for the sole purpose of debugging, and re-writing the code for best practises and debugging purposes.
 * I do not claim ownership of this code, I will be refactoring and debugging.
 */


public class BuggyFunctionsBefore {

    public static void main(String[] args) {

        ArrayList<String> names = new ArrayList<>();
        names.add("Alice");
        names.add("Bob");
        names.add("Charlie");
        names.add(null);
        names.add("David");

        System.out.println("Names in the list:");
        for (int i = 0; i < names.size(); i++) {
            System.out.println(names.get(i));
        }

        System.out.println("Length of the longest name: " + longestName(names));

        printNumbers("10");

        addNames(names, "Eve");
        removeName(names, 3);
        removeName(names, 5);
    }

    public static int longestName(ArrayList<String> names) {
        String longest = null;
        for (String name : names) {
            if (name.length() > longest.length()) {
                longest = name;
            }
        }
        return longest.length();
    }

    public static void printNumbers(int n) {
        for (int i = 1; i <= n; i++) {
            System.out.println(i);
        }

        int sum = 0;
        for (int j = 1; j < n; j++) {
            sum += j;
        }
        System.out.println("Sum: " + sum);
    }

    public static void addNames(ArrayList<String> names, String name) {
        names.add(name);
        System.out.println("Added name: " + name);
    }

    public static void removeName(ArrayList<String> names, int index) {
        if (index < 0 || index >= names.size()) {
            System.out.println("Invalid index");
            return;
        }
        names.remove(index);
        System.out.println("Removed name at index: " + index);
    }
}
